Remove Node 4 from Travis build matrix
This is currently failing because of an error:

> SyntaxError: Unexpected reserved word

I need to fix this, but in the meantime, I'm going to cut down on the
noise by disabling this Node version in Travis.